Repository skhuCloud/skhuCloud, pull requests merged in 2022-05, with the labels that each got.

#38 [#37] Folder, File 순서 수정 및 FileDto imageUrl mapping
  src/main/java/com/skhu/cloud/advice/GlobalControllerAdvice.java
  src/main/java/com/skhu/cloud/controller/DownloadController.java
  src/main/java/com/skhu/cloud/controller/MainController.java
  src/main/java/com/skhu/cloud/dto/DirectoryVersionDto.java
  src/main/java/com/skhu/cloud/dto/FileDto.java
  src/main/java/com/skhu/cloud/dto/FolderVersionDto.java
  src/main/java/com/skhu/cloud/dto/diff/FileDiffDto.java
  src/main/java/com/skhu/cloud/dto/diff/FolderDiffDto.java
  src/main/java/com/skhu/cloud/dto/error/CustomException.java
  src/main/java/com/skhu/cloud/dto/error/EnumModel.java
  src/main/java/com/skhu/cloud/dto/error/Error.java
  src/main/java/com/skhu/cloud/dto/error/ErrorCode.java
  src/main/java/com/skhu/cloud/dto/error/ErrorResponse.java
  src/main/java/com/skhu/cloud/dto/version/FileVersionDto.java
  src/main/java/com/skhu/cloud/dto/version/VersionDto.java
  src/main/java/com/skhu/cloud/model/Content.java
  src/main/java/com/skhu/cloud/service/CreateMokService.java
  src/main/java/com/skhu/cloud/service/DownloadService.java
  src/main/java/com/skhu/cloud/service/FolderService.java
  src/main/java/com/skhu/cloud/service/FolderServiceImpl.java
  src/main/java/com/skhu/cloud/service/Impl/CreateMokServiceImpl.java
  src/main/java/com/skhu/cloud/service/Impl/DownloadServiceImpl.java
  src/main/java/com/skhu/cloud/service/Impl/FolderServiceImpl.java
  src/main/java/com/skhu/cloud/service/Impl/MainServiceImpl.java
  src/main/java/com/skhu/cloud/service/Impl/UserServiceImpl.java
  src/main/java/com/skhu/cloud/service/MainService.java
  src/main/java/com/skhu/cloud/service/UserService.java
  src/main/java/com/skhu/cloud/service/UserServiceImpl.java
  src/main/resources/static/images/css.png
  src/main/resources/static/images/docx.png
  src/main/resources/static/images/file.png
  src/main/resources/static/images/folder.png
  src/main/resources/static/images/html.png
  src/main/resources/static/images/java.png
  src/main/resources/static/images/js.png
  src/main/resources/static/images/md.png
  src/main/resources/static/images/py.png
  src/main/resources/static/images/xlsx.png
  src/main/resources/static/images/xml.png
  src/main/resources/static/js/click.js
  src/main/resources/templates/main.html
  src/test/java/com/skhu/cloud/dto/VersionDtoTest.java
  src/test/java/com/skhu/cloud/service/MokServiceTest.java
Labels: refactor

#43 [feature-42] 2개의 파일버전 비교 구현 완료
  src/main/java/com/skhu/cloud/controller/VersionTestController.java
  src/main/java/com/skhu/cloud/dto/FileDto.java
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/main.html
Labels: feature

#44 [feature-42] 2개 버전 비교 기능 구현 완료-폴더
  src/main/java/com/skhu/cloud/controller/VersionTestController.java
  src/main/resources/templates/folderVersion.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/main.html
Labels: feature

#46 [#42] 사이드바 정렬 조정
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/main.html
Labels: css
