Repository skhuCloud/skhuCloud, pull requests merged in 2022-03, with the labels that each got.

#2 #1 기본적인 패키지 생성
  .gitignore
  .gradle/7.4/checksums/checksums.lock
  .gradle/7.4/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.4/dependencies-accessors/gc.properties
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileChanges/last-build.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  src/main/java/com/skhu/cloud/config/security/CustomUserDetailService.java
  src/main/java/com/skhu/cloud/config/security/JwtAuthenticationFilter.java
  src/main/java/com/skhu/cloud/config/security/JwtTokenProvider.java
  src/main/java/com/skhu/cloud/config/security/WebSecurityConfig.java
  src/main/java/com/skhu/cloud/controller/UserController.java
  src/main/java/com/skhu/cloud/entity/User.java
  src/main/java/com/skhu/cloud/repository/UserRepository.java
  src/main/java/com/skhu/cloud/service/UserService.java
  src/main/java/com/skhu/cloud/service/UserServiceImpl.java
Labels: feature

#4 #1 build.gradle security , jwt 의존성 추가
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: refactor

#8 #1 화면 구현 수정 및 문제 해결 중 중간 PR
  build/classes/java/main/com/skhu/cloud/CloudApplication.class
  build/classes/java/main/com/skhu/cloud/config/security/CustomUserDetailService.class
  build/classes/java/main/com/skhu/cloud/config/security/JwtAuthenticationFilter 2.class
  build/classes/java/main/com/skhu/cloud/config/security/JwtAuthenticationFilter.class
  build/classes/java/main/com/skhu/cloud/config/security/JwtTokenProvider 2.class
  build/classes/java/main/com/skhu/cloud/config/security/JwtTokenProvider.class
  build/classes/java/main/com/skhu/cloud/config/security/WebSecurityConfig 2.class
  build/classes/java/main/com/skhu/cloud/config/security/WebSecurityConfig.class
  build/classes/java/main/com/skhu/cloud/controller/UserController 2.class
  build/classes/java/main/com/skhu/cloud/controller/UserController.class
  build/classes/java/main/com/skhu/cloud/entity/User$UserBuilder.class
  build/classes/java/main/com/skhu/cloud/entity/User.class
  build/classes/java/main/com/skhu/cloud/repository/UserRepository.class
  build/classes/java/main/com/skhu/cloud/service/UserService.class
  build/classes/java/main/com/skhu/cloud/service/UserServiceImpl 2.class
  build/classes/java/main/com/skhu/cloud/service/UserServiceImpl.class
  build/resources/main/application 2.yml
  build/resources/main/templates/login.html
  build/resources/main/templates/signup.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/skhu/cloud/config/security/JwtAuthenticationFilter.java
  src/main/java/com/skhu/cloud/config/security/JwtTokenProvider.java
  src/main/java/com/skhu/cloud/config/security/WebSecurityConfig.java
  src/main/java/com/skhu/cloud/controller/UserController.java
  src/main/java/com/skhu/cloud/entity/User.java
  src/main/java/com/skhu/cloud/filter/CustomFilter.java
  src/main/java/com/skhu/cloud/service/UserServiceImpl.java
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: refactor

#10 #1 화면 기획 및 구현 완료
  build.gradle
  build/classes/java/main/com/skhu/cloud/CloudApplication.class
  build/classes/java/main/com/skhu/cloud/controller/UserController.class
  build/classes/java/main/com/skhu/cloud/entity/User$UserBuilder.class
  build/classes/java/main/com/skhu/cloud/entity/User.class
  build/classes/java/main/com/skhu/cloud/repository/UserRepository.class
  build/classes/java/main/com/skhu/cloud/service/UserService.class
  build/classes/java/main/com/skhu/cloud/service/UserServiceImpl.class
  build/resources/main/templates/login.html
  build/resources/main/templates/signup.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/skhu/cloud/config/security/CustomUserDetailService.java
  src/main/java/com/skhu/cloud/config/security/JwtAuthenticationFilter.java
  src/main/java/com/skhu/cloud/config/security/JwtTokenProvider.java
  src/main/java/com/skhu/cloud/config/security/WebSecurityConfig.java
  src/main/java/com/skhu/cloud/controller/UserController.java
  src/main/java/com/skhu/cloud/entity/User.java
  src/main/java/com/skhu/cloud/filter/CustomFilter.java
  src/main/java/com/skhu/cloud/service/UserService.java
  src/main/java/com/skhu/cloud/service/UserServiceImpl.java
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: refactor

#18 #14 로컬파일 단일 파일 다운로드, .zip 다운로드 구현 완료
  build/classes/java/main/com/skhu/cloud/controller/DownloadController.class
  build/classes/java/main/com/skhu/cloud/controller/MainController.class
  build/classes/java/main/com/skhu/cloud/service/DownloadService.class
  build/resources/main/templates/tables.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/skhu/cloud/controller/DownloadController.java
  src/main/java/com/skhu/cloud/controller/MainController.java
  src/main/java/com/skhu/cloud/service/DownloadService.java
Labels: feature

#20 #14 다운로드 기능 구현 완료
  build/classes/java/main/com/skhu/cloud/controller/DownloadController.class
  build/classes/java/main/com/skhu/cloud/service/DownloadService.class
  build/resources/main/templates/main.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/skhu/cloud/controller/DownloadController.java
  src/main/java/com/skhu/cloud/service/DownloadService.java
  src/main/java/com/skhu/cloud/service/DownloadServiceImpl.java
  src/main/resources/templates/main.html
Labels: enhancement, feature
